name: MLOps CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  train-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build trainer image
        run: |
          docker build -t mlops-trainer -f docker/Dockerfile.train .

      - name: Start MLflow
        run: |
          docker compose -f docker/docker-compose.yml up -d mlflow
          sleep 15

      - name: Run training
        env:
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
        run: |
          docker run \
            --network docker_default \
            -e MLFLOW_TRACKING_URI=$MLFLOW_TRACKING_URI \
            mlops-trainer

      - name: Build API image
        run: |
          docker build -t mlops-api -f docker/Dockerfile.api .

      - name: Stop containers
        run: |
          docker compose -f docker/docker-compose.yml down
